In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("churn_data_raw.csv")

In [3]:
df

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method,Notes
0,C-1001,Male,45,2020-01-15,2023-08-10,5550.65,65.50,No,1,Yes,No,DSL,Yes,No,Month-to-month,Yes,Electronic check,NaN
1,C-1002,Female,32,2019-05-20,2023-09-01,7200.10,89.99,no,0,Yes,Yes,Fiber optic,No,No,One year,Yes,Mailed check,NaN
2,C-1003,NaN,67,2018-11-01,2023-07-15,8500.00,105.75,Yes,3,Yes,Yes,Fiber optic,Yes,Yes,Two year,Yes,Bank transfer (automatic),Account flagged for review
3,C-1004,Female,25,2022-02-10,2023-08-25,950.25,45.00,No,2,Yes,No,DSL,No,Yes,Month-to-month,No,Credit card (automatic),NaN
4,C-1005,Male,51,2021-08-05,2023-09-05,3200.50,75.20,YES,1,Yes,Yes,Fiber optic,Yes,No,One year,Yes,Electronic check,NaN
5,C-1006,Female,29,2023-01-12,2023-08-18,NaN,55.00,No,0,No,-,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,NaN
6,C-1007,Male,72,2017-03-30,2023-06-20,9800.70,115.25,Yes,4,Yes,Yes,FIBER OPTIC,Yes,Yes,Two year,Yes,Credit card (automatic),NaN
7,C-1008,Female,22,2022-09-15,2023-08-30,400.00,50.00,No,1,Yes,No,DSL,No,No,Month-to-month,No,Electronic check,New customer
8,C-1009,Male,48,2020-12-01,NaN,95.50,No,0,Yes,Yes,Fiber optic,No,Yes,One year,Yes,Bank transfer (automatic),NaN,NaN
9,C-1010,female,38,2021-04-22,2023-09-02,4800.90,99.99,No,2,Yes,Yes,Fiber optic,Yes,No,Month-to-month,Yes,Mailed check,NaN
10,C-1011,Male,999,2019-07-14,2023-08-01,6100.30,102.00,Yes,1,Yes,No,DSL,Yes,Yes,Two year,No,Credit card (automatic),Age seems incorrect
11,C-1012,Male,56,2018-02-18,2023-07-28,7500.00,110.50,yes,3,Yes,Yes,Fiber optic,No,No,One year,Yes,Electronic check,NaN

In [4]:
df.drop(columns=["Notes"], inplace=True)

In [5]:
df.head()

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method
0,C-1001,Male,45,2020-01-15,2023-08-10,5550.65,65.50,No,1,Yes,No,DSL,Yes,No,Month-to-month,Yes,Electronic check
1,C-1002,Female,32,2019-05-20,2023-09-01,7200.10,89.99,no,0,Yes,Yes,Fiber optic,No,No,One year,Yes,Mailed check
2,C-1003,NaN,67,2018-11-01,2023-07-15,8500.00,105.75,Yes,3,Yes,Yes,Fiber optic,Yes,Yes,Two year,Yes,Bank transfer (automatic)
3,C-1004,Female,25,2022-02-10,2023-08-25,950.25,45.00,No,2,Yes,No,DSL,No,Yes,Month-to-month,No,Credit card (automatic)
4,C-1005,Male,51,2021-08-05,2023-09-05,3200.50,75.20,YES,1,Yes,Yes,Fiber optic,Yes,No,One year,Yes,Electronic check

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CustomerID               12 non-null     object
 1   Gender                   11 non-null     object
 2   Age                      12 non-null     int64
 3   Subscription_Start_Date  12 non-null     object
 4   Last_Payment_Date        11 non-null     object
 5   Total_Charges            11 non-null     float64
 6   Monthly_Charges          12 non-null     object
 7   Churn                    12 non-null     object
 8   Customer_Service_Calls   12 non-null     object
 9   Phone_Service            12 non-null     object
 10  Multiple_Lines           12 non-null     object
 11  Internet_Service         12 non-null     object
 12  Online_Security          12 non-null     object
 13  Tech_Support             12 non-null     object
 14  Contract                 12 non-null     object
 15  Paperless_Billing        12 non-null     object
 16  Payment_Method           11 non-null     object
dtypes: float64(1), int64(1), object(15)
memory usage: 1.7+ KB

In [7]:
df.replace(r'^\s*$', np.nan, regex=True, inplace=True)
df.replace('-', np.nan, inplace=True)

In [8]:
df

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method
0,C-1001,Male,45,2020-01-15,2023-08-10,5550.65,65.50,No,1,Yes,No,DSL,Yes,No,Month-to-month,Yes,Electronic check
1,C-1002,Female,32,2019-05-20,2023-09-01,7200.10,89.99,no,0,Yes,Yes,Fiber optic,No,No,One year,Yes,Mailed check
2,C-1003,NaN,67,2018-11-01,2023-07-15,8500.00,105.75,Yes,3,Yes,Yes,Fiber optic,Yes,Yes,Two year,Yes,Bank transfer (automatic)
3,C-1004,Female,25,2022-02-10,2023-08-25,950.25,45.00,No,2,Yes,No,DSL,No,Yes,Month-to-month,No,Credit card (automatic)
4,C-1005,Male,51,2021-08-05,2023-09-05,3200.50,75.20,YES,1,Yes,Yes,Fiber optic,Yes,No,One year,Yes,Electronic check
5,C-1006,Female,29,2023-01-12,2023-08-18,NaN,55.00,No,0,No,NaN,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check
6,C-1007,Male,72,2017-03-30,2023-06-20,9800.70,115.25,Yes,4,Yes,Yes,FIBER OPTIC,Yes,Yes,Two year,Yes,Credit card (automatic)
7,C-1008,Female,22,2022-09-15,2023-08-30,400.00,50.00,No,1,Yes,No,DSL,No,No,Month-to-month,No,Electronic check
8,C-1009,Male,48,2020-12-01,NaN,95.50,No,0,Yes,Yes,Fiber optic,No,Yes,One year,Yes,Bank transfer (automatic),NaN
9,C-1010,female,38,2021-04-22,2023-09-02,4800.90,99.99,No,2,Yes,Yes,Fiber optic,Yes,No,Month-to-month,Yes,Mailed check
10,C-1011,Male,999,2019-07-14,2023-08-01,6100.30,102.00,Yes,1,Yes,No,DSL,Yes,Yes,Two year,No,Credit card (automatic)
11,C-1012,Male,56,2018-02-18,2023-07-28,7500.00,110.50,yes,3,Yes,Yes,Fiber optic,No,No,One year,Yes,Electronic check

In [9]:
shifted_row_index = df[df['Churn'] == '0'].index

In [10]:
shifted_indices = [shifted_row_index]
shifted_indices

[Index([8], dtype='int64')]

In [11]:
for idx in shifted_indices:
    
    df.loc[idx, 'Payment_Method'] = df.loc[idx, 'Paperless_Billing']
    df.loc[idx, 'Paperless_Billing'] = df.loc[idx, 'Contract']
    df.loc[idx, 'Contract'] = df.loc[idx, 'Tech_Support']
    df.loc[idx, 'Tech_Support'] = df.loc[idx, 'Online_Security']
    df.loc[idx, 'Online_Security'] = df.loc[idx, 'Internet_Service']
    df.loc[idx, 'Internet_Service'] = df.loc[idx, 'Multiple_Lines']
    df.loc[idx, 'Multiple_Lines'] = df.loc[idx, 'Phone_Service']
    df.loc[idx, 'Phone_Service'] = df.loc[idx, 'Customer_Service_Calls']
    df.loc[idx, 'Customer_Service_Calls'] = df.loc[idx, 'Churn']
    df.loc[idx, 'Churn'] = df.loc[idx, 'Monthly_Charges']
    df.loc[idx, 'Monthly_Charges'] = df.loc[idx, 'Total_Charges']
    df.loc[idx, 'Total_Charges'] = np.nan

In [12]:
df

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method
0,C-1001,Male,45,2020-01-15,2023-08-10,5550.65,65.50,No,1,Yes,No,DSL,Yes,No,Month-to-month,Yes,Electronic check
1,C-1002,Female,32,2019-05-20,2023-09-01,7200.10,89.99,no,0,Yes,Yes,Fiber optic,No,No,One year,Yes,Mailed check
2,C-1003,NaN,67,2018-11-01,2023-07-15,8500.00,105.75,Yes,3,Yes,Yes,Fiber optic,Yes,Yes,Two year,Yes,Bank transfer (automatic)
3,C-1004,Female,25,2022-02-10,2023-08-25,950.25,45.00,No,2,Yes,No,DSL,No,Yes,Month-to-month,No,Credit card (automatic)
4,C-1005,Male,51,2021-08-05,2023-09-05,3200.50,75.20,YES,1,Yes,Yes,Fiber optic,Yes,No,One year,Yes,Electronic check
5,C-1006,Female,29,2023-01-12,2023-08-18,NaN,55.00,No,0,No,NaN,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check
6,C-1007,Male,72,2017-03-30,2023-06-20,9800.70,115.25,Yes,4,Yes,Yes,FIBER OPTIC,Yes,Yes,Two year,Yes,Credit card (automatic)
7,C-1008,Female,22,2022-09-15,2023-08-30,400.00,50.00,No,1,Yes,No,DSL,No,No,Month-to-month,No,Electronic check
8,C-1009,Male,48,2020-12-01,NaN,NaN,95.5,No,0,Yes,Yes,Fiber optic,No,Yes,One year,Yes,Bank transfer (automatic)
9,C-1010,female,38,2021-04-22,2023-09-02,4800.90,99.99,No,2,Yes,Yes,Fiber optic,Yes,No,Month-to-month,Yes,Mailed check
10,C-1011,Male,999,2019-07-14,2023-08-01,6100.30,102.00,Yes,1,Yes,No,DSL,Yes,Yes,Two year,No,Credit card (automatic)
11,C-1012,Male,56,2018-02-18,2023-07-28,7500.00,110.50,yes,3,Yes,Yes,Fiber optic,No,No,One year,Yes,Electronic check

In [13]:
list_cols_0 = ['Total_Charges', 'Monthly_Charges', 'Customer_Service_Calls']
for col in list_cols_0:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [14]:
list_cols_1 = ['Subscription_Start_Date', 'Last_Payment_Date']
for col in list_cols_1:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [15]:
df.loc[df['Age'] > 100, 'Age'] = np.nan

In [16]:
df

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method
0,C-1001,Male,45.0,2020-01-15,2023-08-10,5550.65,65.50,No,1,Yes,No,DSL,Yes,No,Month-to-month,Yes,Electronic check
1,C-1002,Female,32.0,2019-05-20,2023-09-01,7200.10,89.99,no,0,Yes,Yes,Fiber optic,No,No,One year,Yes,Mailed check
2,C-1003,NaN,67.0,2018-11-01,2023-07-15,8500.00,105.75,Yes,3,Yes,Yes,Fiber optic,Yes,Yes,Two year,Yes,Bank transfer (automatic)
3,C-1004,Female,25.0,2022-02-10,2023-08-25,950.25,45.00,No,2,Yes,No,DSL,No,Yes,Month-to-month,No,Credit card (automatic)
4,C-1005,Male,51.0,2021-08-05,2023-09-05,3200.50,75.20,YES,1,Yes,Yes,Fiber optic,Yes,No,One year,Yes,Electronic check
5,C-1006,Female,29.0,2023-01-12,2023-08-18,NaN,55.00,No,0,No,NaN,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check
6,C-1007,Male,72.0,2017-03-30,2023-06-20,9800.70,115.25,Yes,4,Yes,Yes,FIBER OPTIC,Yes,Yes,Two year,Yes,Credit card (automatic)
7,C-1008,Female,22.0,2022-09-15,2023-08-30,400.00,50.00,No,1,Yes,No,DSL,No,No,Month-to-month,No,Electronic check
8,C-1009,Male,48.0,2020-12-01,NaT,NaN,95.50,No,0,Yes,Yes,Fiber optic,No,Yes,One year,Yes,Bank transfer (automatic)
9,C-1010,female,38.0,2021-04-22,2023-09-02,4800.90,99.99,No,2,Yes,Yes,Fiber optic,Yes,No,Month-to-month,Yes,Mailed check
10,C-1011,Male,NaN,2019-07-14,2023-08-01,6100.30,102.00,Yes,1,Yes,No,DSL,Yes,Yes,Two year,No,Credit card (automatic)
11,C-1012,Male,56.0,2018-02-18,2023-07-28,7500.00,110.50,yes,3,Yes,Yes,Fiber optic,No,No,One year,Yes,Electronic check

In [17]:
list_cols_2 = ['Age', 'Total_Charges', 'Monthly_Charges']
for col in list_cols_2:
    df[col] = df[col].fillna(df[col].median())

In [18]:
df

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method
0,C-1001,Male,45.0,2020-01-15,2023-08-10,5550.650,65.50,No,1,Yes,No,DSL,Yes,No,Month-to-month,Yes,Electronic check
1,C-1002,Female,32.0,2019-05-20,2023-09-01,7200.100,89.99,no,0,Yes,Yes,Fiber optic,No,No,One year,Yes,Mailed check
2,C-1003,NaN,67.0,2018-11-01,2023-07-15,8500.000,105.75,Yes,3,Yes,Yes,Fiber optic,Yes,Yes,Two year,Yes,Bank transfer (automatic)
3,C-1004,Female,25.0,2022-02-10,2023-08-25,950.250,45.00,No,2,Yes,No,DSL,No,Yes,Month-to-month,No,Credit card (automatic)
4,C-1005,Male,51.0,2021-08-05,2023-09-05,3200.500,75.20,YES,1,Yes,Yes,Fiber optic,Yes,No,One year,Yes,Electronic check
5,C-1006,Female,29.0,2023-01-12,2023-08-18,5825.475,55.00,No,0,No,NaN,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check
6,C-1007,Male,72.0,2017-03-30,2023-06-20,9800.700,115.25,Yes,4,Yes,Yes,FIBER OPTIC,Yes,Yes,Two year,Yes,Credit card (automatic)
7,C-1008,Female,22.0,2022-09-15,2023-08-30,400.000,50.00,No,1,Yes,No,DSL,No,No,Month-to-month,No,Electronic check
8,C-1009,Male,48.0,2020-12-01,NaT,5825.475,95.50,No,0,Yes,Yes,Fiber optic,No,Yes,One year,Yes,Bank transfer (automatic)
9,C-1010,female,38.0,2021-04-22,2023-09-02,4800.900,99.99,No,2,Yes,Yes,Fiber optic,Yes,No,Month-to-month,Yes,Mailed check
10,C-1011,Male,45.0,2019-07-14,2023-08-01,6100.300,102.00,Yes,1,Yes,No,DSL,Yes,Yes,Two year,No,Credit card (automatic)
11,C-1012,Male,56.0,2018-02-18,2023-07-28,7500.000,110.50,yes,3,Yes,Yes,Fiber optic,No,No,One year,Yes,Electronic check

In [19]:
df['Last_Payment_Date']

0    2023-08-10
1    2023-09-01
2    2023-07-15
3    2023-08-25
4    2023-09-05
5    2023-08-18
6    2023-06-20
7    2023-08-30
8           NaT
9    2023-09-02
10   2023-08-01
11   2023-07-28
Name: Last_Payment_Date, dtype: datetime64[ns]

In [20]:
df['Last_Payment_Date'] = df['Last_Payment_Date'].fillna(df['Last_Payment_Date'].max())

In [21]:
df['Last_Payment_Date']

0    2023-08-10
1    2023-09-01
2    2023-07-15
3    2023-08-25
4    2023-09-05
5    2023-08-18
6    2023-06-20
7    2023-08-30
8    2023-09-05
9    2023-09-02
10   2023-08-01
11   2023-07-28
Name: Last_Payment_Date, dtype: datetime64[ns]

In [22]:
df.loc[df['Phone_Service'] == 'No', 'Multiple_Lines'] = 'No'

In [23]:
df['Gender']

0       Male
1     Female
2        NaN
3     Female
4       Male
5     Female
6       Male
7     Female
8       Male
9     female
10      Male
11      Male
Name: Gender, dtype: object

In [24]:
df['Gender'] = df['Gender'].fillna('Unknown')

In [25]:
df['Gender']

0        Male
1      Female
2     Unknown
3      Female
4        Male
5      Female
6        Male
7      Female
8        Male
9      female
10       Male
11       Male
Name: Gender, dtype: object

In [26]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [27]:
df

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method
0,C-1001,Male,45.0,2020-01-15,2023-08-10,5550.650,65.50,No,1,Yes,No,DSL,Yes,No,Month-to-month,Yes,Electronic check
1,C-1002,Female,32.0,2019-05-20,2023-09-01,7200.100,89.99,no,0,Yes,Yes,Fiber optic,No,No,One year,Yes,Mailed check
2,C-1003,Unknown,67.0,2018-11-01,2023-07-15,8500.000,105.75,Yes,3,Yes,Yes,Fiber optic,Yes,Yes,Two year,Yes,Bank transfer (automatic)
3,C-1004,Female,25.0,2022-02-10,2023-08-25,950.250,45.00,No,2,Yes,No,DSL,No,Yes,Month-to-month,No,Credit card (automatic)
4,C-1005,Male,51.0,2021-08-05,2023-09-05,3200.500,75.20,YES,1,Yes,Yes,Fiber optic,Yes,No,One year,Yes,Electronic check
5,C-1006,Female,29.0,2023-01-12,2023-08-18,5825.475,55.00,No,0,No,No,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check
6,C-1007,Male,72.0,2017-03-30,2023-06-20,9800.700,115.25,Yes,4,Yes,Yes,FIBER OPTIC,Yes,Yes,Two year,Yes,Credit card (automatic)
7,C-1008,Female,22.0,2022-09-15,2023-08-30,400.000,50.00,No,1,Yes,No,DSL,No,No,Month-to-month,No,Electronic check
8,C-1009,Male,48.0,2020-12-01,2023-09-05,5825.475,95.50,No,0,Yes,Yes,Fiber optic,No,Yes,One year,Yes,Bank transfer (automatic)
9,C-1010,female,38.0,2021-04-22,2023-09-02,4800.900,99.99,No,2,Yes,Yes,Fiber optic,Yes,No,Month-to-month,Yes,Mailed check
10,C-1011,Male,45.0,2019-07-14,2023-08-01,6100.300,102.00,Yes,1,Yes,No,DSL,Yes,Yes,Two year,No,Credit card (automatic)
11,C-1012,Male,56.0,2018-02-18,2023-07-28,7500.000,110.50,yes,3,Yes,Yes,Fiber optic,No,No,One year,Yes,Electronic check

In [28]:
df['Customer_Service_Calls'] = df['Customer_Service_Calls'].fillna(0)

In [29]:
df

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method
0,C-1001,Male,45.0,2020-01-15,2023-08-10,5550.650,65.50,No,1,Yes,No,DSL,Yes,No,Month-to-month,Yes,Electronic check
1,C-1002,Female,32.0,2019-05-20,2023-09-01,7200.100,89.99,no,0,Yes,Yes,Fiber optic,No,No,One year,Yes,Mailed check
2,C-1003,Unknown,67.0,2018-11-01,2023-07-15,8500.000,105.75,Yes,3,Yes,Yes,Fiber optic,Yes,Yes,Two year,Yes,Bank transfer (automatic)
3,C-1004,Female,25.0,2022-02-10,2023-08-25,950.250,45.00,No,2,Yes,No,DSL,No,Yes,Month-to-month,No,Credit card (automatic)
4,C-1005,Male,51.0,2021-08-05,2023-09-05,3200.500,75.20,YES,1,Yes,Yes,Fiber optic,Yes,No,One year,Yes,Electronic check
5,C-1006,Female,29.0,2023-01-12,2023-08-18,5825.475,55.00,No,0,No,No,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check
6,C-1007,Male,72.0,2017-03-30,2023-06-20,9800.700,115.25,Yes,4,Yes,Yes,FIBER OPTIC,Yes,Yes,Two year,Yes,Credit card (automatic)
7,C-1008,Female,22.0,2022-09-15,2023-08-30,400.000,50.00,No,1,Yes,No,DSL,No,No,Month-to-month,No,Electronic check
8,C-1009,Male,48.0,2020-12-01,2023-09-05,5825.475,95.50,No,0,Yes,Yes,Fiber optic,No,Yes,One year,Yes,Bank transfer (automatic)
9,C-1010,female,38.0,2021-04-22,2023-09-02,4800.900,99.99,No,2,Yes,Yes,Fiber optic,Yes,No,Month-to-month,Yes,Mailed check
10,C-1011,Male,45.0,2019-07-14,2023-08-01,6100.300,102.00,Yes,1,Yes,No,DSL,Yes,Yes,Two year,No,Credit card (automatic)
11,C-1012,Male,56.0,2018-02-18,2023-07-28,7500.000,110.50,yes,3,Yes,Yes,Fiber optic,No,No,One year,Yes,Electronic check

In [30]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip().str.title()

In [31]:
df

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method
0,C-1001,Male,45.0,2020-01-15,2023-08-10,5550.650,65.50,No,1,Yes,No,Dsl,Yes,No,Month-To-Month,Yes,Electronic Check
1,C-1002,Female,32.0,2019-05-20,2023-09-01,7200.100,89.99,No,0,Yes,Yes,Fiber Optic,No,No,One Year,Yes,Mailed Check
2,C-1003,Unknown,67.0,2018-11-01,2023-07-15,8500.000,105.75,Yes,3,Yes,Yes,Fiber Optic,Yes,Yes,Two Year,Yes,Bank Transfer (Automatic)
3,C-1004,Female,25.0,2022-02-10,2023-08-25,950.250,45.00,No,2,Yes,No,Dsl,No,Yes,Month-To-Month,No,Credit Card (Automatic)
4,C-1005,Male,51.0,2021-08-05,2023-09-05,3200.500,75.20,Yes,1,Yes,Yes,Fiber Optic,Yes,No,One Year,Yes,Electronic Check
5,C-1006,Female,29.0,2023-01-12,2023-08-18,5825.475,55.00,No,0,No,No,No Internet Service,No Internet Service,No Internet Service,Month-To-Month,Yes,Mailed Check
6,C-1007,Male,72.0,2017-03-30,2023-06-20,9800.700,115.25,Yes,4,Yes,Yes,Fiber Optic,Yes,Yes,Two Year,Yes,Credit Card (Automatic)
7,C-1008,Female,22.0,2022-09-15,2023-08-30,400.000,50.00,No,1,Yes,No,Dsl,No,No,Month-To-Month,No,Electronic Check
8,C-1009,Male,48.0,2020-12-01,2023-09-05,5825.475,95.50,No,0,Yes,Yes,Fiber Optic,No,Yes,One Year,Yes,Bank Transfer (Automatic)
9,C-1010,Female,38.0,2021-04-22,2023-09-02,4800.900,99.99,No,2,Yes,Yes,Fiber Optic,Yes,No,Month-To-Month,Yes,Mailed Check
10,C-1011,Male,45.0,2019-07-14,2023-08-01,6100.300,102.00,Yes,1,Yes,No,Dsl,Yes,Yes,Two Year,No,Credit Card (Automatic)
11,C-1012,Male,56.0,2018-02-18,2023-07-28,7500.000,110.50,Yes,3,Yes,Yes,Fiber Optic,No,No,One Year,Yes,Electronic Check

In [32]:
df.replace('No Internet Service', 'None', inplace=True)

In [33]:
df

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method
0,C-1001,Male,45.0,2020-01-15,2023-08-10,5550.650,65.50,No,1,Yes,No,Dsl,Yes,No,Month-To-Month,Yes,Electronic Check
1,C-1002,Female,32.0,2019-05-20,2023-09-01,7200.100,89.99,No,0,Yes,Yes,Fiber Optic,No,No,One Year,Yes,Mailed Check
2,C-1003,Unknown,67.0,2018-11-01,2023-07-15,8500.000,105.75,Yes,3,Yes,Yes,Fiber Optic,Yes,Yes,Two Year,Yes,Bank Transfer (Automatic)
3,C-1004,Female,25.0,2022-02-10,2023-08-25,950.250,45.00,No,2,Yes,No,Dsl,No,Yes,Month-To-Month,No,Credit Card (Automatic)
4,C-1005,Male,51.0,2021-08-05,2023-09-05,3200.500,75.20,Yes,1,Yes,Yes,Fiber Optic,Yes,No,One Year,Yes,Electronic Check
5,C-1006,Female,29.0,2023-01-12,2023-08-18,5825.475,55.00,No,0,No,No,None,None,None,Month-To-Month,Yes,Mailed Check
6,C-1007,Male,72.0,2017-03-30,2023-06-20,9800.700,115.25,Yes,4,Yes,Yes,Fiber Optic,Yes,Yes,Two Year,Yes,Credit Card (Automatic)
7,C-1008,Female,22.0,2022-09-15,2023-08-30,400.000,50.00,No,1,Yes,No,Dsl,No,No,Month-To-Month,No,Electronic Check
8,C-1009,Male,48.0,2020-12-01,2023-09-05,5825.475,95.50,No,0,Yes,Yes,Fiber Optic,No,Yes,One Year,Yes,Bank Transfer (Automatic)
9,C-1010,Female,38.0,2021-04-22,2023-09-02,4800.900,99.99,No,2,Yes,Yes,Fiber Optic,Yes,No,Month-To-Month,Yes,Mailed Check
10,C-1011,Male,45.0,2019-07-14,2023-08-01,6100.300,102.00,Yes,1,Yes,No,Dsl,Yes,Yes,Two Year,No,Credit Card (Automatic)
11,C-1012,Male,56.0,2018-02-18,2023-07-28,7500.000,110.50,Yes,3,Yes,Yes,Fiber Optic,No,No,One Year,Yes,Electronic Check

In [34]:
df['Age'] = df['Age'].astype(int)
df['Customer_Service_Calls'] = df['Customer_Service_Calls'].astype(int)

In [35]:
df

,CustomerID,Gender,Age,Subscription_Start_Date,Last_Payment_Date,Total_Charges,Monthly_Charges,Churn,Customer_Service_Calls,Phone_Service,Multiple_Lines,Internet_Service,Online_Security,Tech_Support,Contract,Paperless_Billing,Payment_Method
0,C-1001,Male,45,2020-01-15,2023-08-10,5550.650,65.50,No,1,Yes,No,Dsl,Yes,No,Month-To-Month,Yes,Electronic Check
1,C-1002,Female,32,2019-05-20,2023-09-01,7200.100,89.99,No,0,Yes,Yes,Fiber Optic,No,No,One Year,Yes,Mailed Check
2,C-1003,Unknown,67,2018-11-01,2023-07-15,8500.000,105.75,Yes,3,Yes,Yes,Fiber Optic,Yes,Yes,Two Year,Yes,Bank Transfer (Automatic)
3,C-1004,Female,25,2022-02-10,2023-08-25,950.250,45.00,No,2,Yes,No,Dsl,No,Yes,Month-To-Month,No,Credit Card (Automatic)
4,C-1005,Male,51,2021-08-05,2023-09-05,3200.500,75.20,Yes,1,Yes,Yes,Fiber Optic,Yes,No,One Year,Yes,Electronic Check
5,C-1006,Female,29,2023-01-12,2023-08-18,5825.475,55.00,No,0,No,No,None,None,None,Month-To-Month,Yes,Mailed Check
6,C-1007,Male,72,2017-03-30,2023-06-20,9800.700,115.25,Yes,4,Yes,Yes,Fiber Optic,Yes,Yes,Two Year,Yes,Credit Card (Automatic)
7,C-1008,Female,22,2022-09-15,2023-08-30,400.000,50.00,No,1,Yes,No,Dsl,No,No,Month-To-Month,No,Electronic Check
8,C-1009,Male,48,2020-12-01,2023-09-05,5825.475,95.50,No,0,Yes,Yes,Fiber Optic,No,Yes,One Year,Yes,Bank Transfer (Automatic)
9,C-1010,Female,38,2021-04-22,2023-09-02,4800.900,99.99,No,2,Yes,Yes,Fiber Optic,Yes,No,Month-To-Month,Yes,Mailed Check
10,C-1011,Male,45,2019-07-14,2023-08-01,6100.300,102.00,Yes,1,Yes,No,Dsl,Yes,Yes,Two Year,No,Credit Card (Automatic)
11,C-1012,Male,56,2018-02-18,2023-07-28,7500.000,110.50,Yes,3,Yes,Yes,Fiber Optic,No,No,One Year,Yes,Electronic Check

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CustomerID               12 non-null     object
 1   Gender                   12 non-null     object
 2   Age                      12 non-null     int32
 3   Subscription_Start_Date  12 non-null     datetime64[ns]
 4   Last_Payment_Date        12 non-null     datetime64[ns]
 5   Total_Charges            12 non-null     float64
 6   Monthly_Charges          12 non-null     float64
 7   Churn                    12 non-null     object
 8   Customer_Service_Calls   12 non-null     int32
 9   Phone_Service            12 non-null     object
 10  Multiple_Lines           12 non-null     object
 11  Internet_Service         12 non-null     object
 12  Online_Security          12 non-null     object
 13  Tech_Support             12 non-null     object
 14  Contract                 12 non-null     object
 15  Paperless_Billing        12 non-null     object
 16  Payment_Method           12 non-null     object
dtypes: datetime64[ns](2), float64(2), int32(2), object(11)
memory usage: 1.6+ KB